### ISSUE TITLE
Crashes on Windows

### ISSUE THREAD

**Issue by iSeiryu** [loft-sh/devspace#1164]
**What happened?**  
Any devspace command started throwing one of these exceptions
```bash
Exception 0xc0000005 0x0 0x7ff8f61f0fff 0x5fd0000
PC=0x5fd0000

runtime: unknown pc 0x5fd0000
stack: frame={sp:0x3d2e820, fp:0x0} stack=[0x0,0x3d2ff00)
0000000003d2e720:  0000000003d2e768  0000000003d2e790
0000000003d2e730:  0000000003d2e758  0000000003d2e750
0000000003d2e740:  0000000003d2e754  0000000003db0000
0000000003d2e750:  0000000000000000  0000000000000000
0000000003d2e760:  0000000000000000  0000000000000005
0000000003d2e770:  0000000003d2e8b8  00007ff8f3b99f38
0000000003d2e780:  0000000003eb3930  00007ff8f60146ce
0000000003d2e790:  00007ff8f5ff00e8  0000000003edead0
0000000003d2e7a0:  00007ff8f3b99f32  0000000003d2e7f0
0000000003d2e7b0:  004f0044004e0049  0053005c00530057
0000000003d2e7c0:  0000000003eb3930  0000000000000000
0000000003d2e7d0:  0000000003ec59d0  006c006400050005
0000000003d2e7e0:  00007ff8f3b99f32  0000000000000000
0000000003d2e7f0:  00007ff800000000  00007ff8f5ff00e8
0000000003d2e800:  0000000000000000  0000000000000000
0000000003d2e810:  0000000000000001  00007ff8f6013783
0000000003d2e820: <0000000000000001  0000000000000000
0000000003d2e830:  0000000000000000  0000000003d2e928
0000000003d2e840:  0000000000000000  0000000000000000
0000000003d2e850:  0000000000000000  0000000000000000
0000000003d2e860:  0000000003edead0  00007ff8f6140f00
0000000003d2e870:  0000000003eb3930  00007ff8f6143520
0000000003d2e880:  000000000000097d  00007ff8f2b8ccb8
0000000003d2e890:  00007ff8f2b8a148  00007ff8f6140f28
0000000003d2e8a0:  00007ff8f6153d4f  00007ff8f2b80000
0000000003d2e8b0:  00007ff8f6145b14  00007ff8f6070aa0
0000000003d2e8c0:  0000000000000000  0000000000000000
0000000003d2e8d0:  0000000000000000  0000000000000000
0000000003d2e8e0:  0000000003edf320  0000000000000040
0000000003d2e8f0:  0000000000000003  00007ff8f615a3f0
0000000003d2e900:  0000000000000001  0000000003d2eb00
0000000003d2e910:  0000000003ec59d0  00007ff8f6051448
runtime: unknown pc 0x5fd0000
stack: frame={sp:0x3d2e820, fp:0x0} stack=[0x0,0x3d2ff00)
0000000003d2e720:  0000000003d2e768  0000000003d2e790
0000000003d2e730:  0000000003d2e758  0000000003d2e750
0000000003d2e740:  0000000003d2e754  0000000003db0000
0000000003d2e750:  0000000000000000  0000000000000000
0000000003d2e760:  0000000000000000  0000000000000005
0000000003d2e770:  0000000003d2e8b8  00007ff8f3b99f38
0000000003d2e780:  0000000003eb3930  00007ff8f60146ce
0000000003d2e790:  00007ff8f5ff00e8  0000000003edead0
0000000003d2e7a0:  00007ff8f3b99f32  0000000003d2e7f0
0000000003d2e7b0:  004f0044004e0049  0053005c00530057
0000000003d2e7c0:  0000000003eb3930  0000000000000000
0000000003d2e7d0:  0000000003ec59d0  006c006400050005
0000000003d2e7e0:  00007ff8f3b99f32  0000000000000000
0000000003d2e7f0:  00007ff800000000  00007ff8f5ff00e8
0000000003d2e800:  0000000000000000  0000000000000000
0000000003d2e810:  0000000000000001  00007ff8f6013783
0000000003d2e820: <0000000000000001  0000000000000000
0000000003d2e830:  0000000000000000  0000000003d2e928
0000000003d2e840:  0000000000000000  0000000000000000
0000000003d2e850:  0000000000000000  0000000000000000
0000000003d2e860:  0000000003edead0  00007ff8f6140f00
0000000003d2e870:  0000000003eb3930  00007ff8f6143520
0000000003d2e880:  000000000000097d  00007ff8f2b8ccb8
0000000003d2e890:  00007ff8f2b8a148  00007ff8f6140f28
0000000003d2e8a0:  00007ff8f6153d4f  00007ff8f2b80000
0000000003d2e8b0:  00007ff8f6145b14  00007ff8f6070aa0
0000000003d2e8c0:  0000000000000000  0000000000000000
0000000003d2e8d0:  0000000000000000  0000000000000000
0000000003d2e8e0:  0000000003edf320  0000000000000040
0000000003d2e8f0:  0000000000000003  00007ff8f615a3f0
0000000003d2e900:  0000000000000001  0000000003d2eb00
0000000003d2e910:  0000000003ec59d0  00007ff8f6051448
rax     0x7ff8f2b8d85c
rbx     0x7ff8f2b8d85a
rcx     0x41
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x7ff8f2cd9f00
rsp     0x3d2e820
r8      0x0
r9      0x0
r10     0x0
r11     0x97c
r12     0xc000007a
r13     0x0
r14     0x7ff8f2b8d85c
r15     0x7ff8f5ff0000
rip     0x5fd0000
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
```

Another one
```bash
Exception 0xc0000005 0x0 0x7ff8f61f0fff 0x70e0000
PC=0x70e0000

syscall.loadsystemlibrary(0xc000046b00, 0xc00004e300, 0xc00004e300, 0x20)
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/runtime/syscall_windows.go:136 +0xe7
syscall.LoadDLL(0x21fe88c, 0xb, 0x43a7b3, 0xc000082000, 0x200000003)
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/syscall/dll_windows.go:80 +0x15e
syscall.(*LazyDLL).Load(0xc0000041a0, 0x0, 0x0)
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/syscall/dll_windows.go:236 +0xbb
syscall.(*LazyProc).Find(0xc0000a5b00, 0x0, 0x0)
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/syscall/dll_windows.go:291 +0xbc
syscall.(*LazyProc).mustFind(0xc0000a5b00)
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/syscall/dll_windows.go:309 +0x32
syscall.(*LazyProc).Addr(0xc0000a5b00, 0xc0000cdc28)
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/syscall/dll_windows.go:318 +0x32
syscall.GetUserProfileDirectory(0x23c, 0xc0000e6340, 0xc0000cdc18, 0xc0000e6340, 0x0)
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/syscall/zsyscall_windows.go:1910 +0x38
syscall.Token.GetUserProfileDirectory(0x23c, 0xc000048420, 0x2c, 0x0, 0x0)
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/syscall/security_windows.go:368 +0x8a
os/user.current(0x0, 0x0, 0x0)
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/os/user/lookup_windows.go:222 +0x1c7
os/user.Current.func1()
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/os/user/lookup.go:15 +0x29
sync.(*Once).doSlow(0x3af7f80, 0x2385038)
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/sync/once.go:66 +0xea
sync.(*Once).Do(...)
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/sync/once.go:57
os/user.Current(0xc000050a10, 0xd, 0x218da15)
        /Users/runner/hostedtoolcache/go/1.13.15/x64/src/os/user/lookup.go:15 +0xf9
k8s.io/klog.init.1()
        /Users/runner/work/devspace/devspace/vendor/k8s.io/klog/klog_file.go:58 +0x48

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x3af93a0)
        /Users/runner/work/devspace/devspace/vendor/k8s.io/klog/klog.go:1010 +0x92
created by k8s.io/klog.init.0
        /Users/runner/work/devspace/devspace/vendor/k8s.io/klog/klog.go:411 +0xdd
rax     0x7ff8f3625784
rbx     0x7ff8f3625782
rcx     0x41
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x0
rsp     0x3d2f4f0
r8      0x0
r9      0x0
r10     0x0
r11     0x97c
r12     0xc000007a
r13     0x0
r14     0x7ff8f3625784
r15     0x7ff8f5ff0000
rip     0x70e0000
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
```
**What did you expect to happen instead?**  
The command to execute as normal

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Run "devspace" in a terminal on Windows.

**Local Environment:**  
- DevSpace Version: 5.0.2
- Operating System: windows 
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: aws and Docker Desktop
- Kubernetes Version: 
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  
It was working just fine for a month and all of a sudden it started throwing the exceptions. I tried to replace the current .exe file with a freshly downloaded from here https://github.com/devspace-cloud/devspace/releases/download/v5.0.2/devspace-windows-amd64.exe but the result is the same. I tried to run it from CMD and Powershell.

```kubectl``` commands work as expected.

Docker Desktop details
![image](https://user-images.githubusercontent.com/129137/92133860-e17be980-edd6-11ea-88a5-e58ee0ccc2ab.png)

/kind bug

**Comment by iSeiryu** [comment]
It still works inside WSL on the same machine but not on Windows itself.

**Comment by FabianKramm** [comment]
@iSeiryu thanks for opening this issue! We tested this on our windows machines, but it works without any issues. From the error message it seems there is a problem loading your UserProfileDirectory. Do you have any special configuration made there?

**Comment by iSeiryu** [comment]
@FabianKramm Not that I'm aware of, the folder structures and the environment variables are the same.
I can run ```echo %USERPROFILE%``` or ```cd ~/.``` and it shows the correct info.
Are there any special system/environment variables devspace x64 looks for?
devspace-windows-386.exe version works just fine.

**Comment by FabianKramm** [comment]
@iSeiryu strange, do you have any other issues with 64bit programs?

**Comment by iSeiryu** [comment]
@FabianKramm Not that I'm aware of.

**Comment by iSeiryu** [comment]
It just happened for another dev who installed it for the first time.

**Comment by LukasGentele** [comment]
@iSeiryu can you send me the output of `systeminfo` for your computer and for the one of your other dev?

**Comment by iSeiryu** [comment]
Mine. I'll get the other one later.
```
❯ systeminfo

Host Name:                 hidden
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          hidden
Registered Organization:   N/A
Product ID:                hidden
Original Install Date:     5/27/2020, 7:18:47 PM
System Boot Time:          9/24/2020, 10:00:00 AM
System Manufacturer:       Dell Inc.
System Model:              XPS 15 7590
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 13 GenuineIntel ~2400 Mhz
BIOS Version:              Dell Inc. 1.8.1, 7/3/2020
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,495 MB
Available Physical Memory: 13,209 MB
Virtual Memory: Max Size:  37,359 MB
Virtual Memory: Available: 4,815 MB
Virtual Memory: In Use:    32,544 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\hidden
Hotfix(s):                 10 Hotfix(s) Installed.
                           [01]: KB4576478
                           [02]: KB4537759
                           [03]: KB4557968
                           [04]: KB4559309
                           [05]: KB4560366
                           [06]: KB4561600
                           [07]: KB4566785
                           [08]: KB4570334
                           [09]: KB4577266
                           [10]: KB4571756
Network Card(s):           4 NIC(s) Installed.
                           [01]: hidden
                           [02]: hidden
                           [03]: hidden
                           [04]: hidden
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

**Comment by iSeiryu** [comment]
Another dev's machine (pretty much same as mine).
```
❯ systeminfo

Host Name:                 hidden
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          hidden
Registered Organization:   N/A
Product ID:                hidden
Original Install Date:     6/30/2020, 12:59:16 AM
System Boot Time:          9/13/2020, 10:36:15 PM
System Manufacturer:       Dell Inc.
System Model:              XPS 15 7590
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 13 GenuineIntel ~2400 Mhz
BIOS Version:              Dell Inc. 1.8.1, 7/3/2020
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,495 MB
Available Physical Memory: 12,723 MB
Virtual Memory: Max Size:  40,519 MB
Virtual Memory: Available: 4,494 MB
Virtual Memory: In Use:    36,025 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\hidden
Hotfix(s):                 8 Hotfix(s) Installed.
                           [01]: KB4576478
                           [02]: KB4559309
                           [03]: KB4560366
                           [04]: KB4561600
                           [05]: KB4566785
                           [06]: KB4570334
                           [07]: KB4577266
                           [08]: KB4571756
Network Card(s):           6 NIC(s) Installed.
                           [01]: hidden
                           [02]: hidden
                           [03]: hidden
                           [04]: hidden
                           [05]: hidden
                           [06]: hidden
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

**Comment by LukasGentele** [comment]
@iSeiryu Thanks! We'll be taking another close look at this. One info upfront: Please, feel free to just use the 32bit version since it is exactly the same as the 64bit version with the only difference that the 64bit version can use more RAM but DevSpace does not need a whole lot of memory, so you should be fine using the 32bit version. 

If we need more information on your environment, I'll let you know. Thanks for providing so many details so quickly.

**Comment by Pavel910** [comment]
After following this issue https://github.com/pulumi/pulumi/issues/6093#issuecomment-773579956, the solution is to remove Webroot antivirus. For our user that was the exact antivirus causing problems, but there may be others causing the same issue. Confirmed to help on 3 different PCs. 

Hope this helps anyone 🍻

**Comment by iSeiryu** [comment]
We do have Webroot too. Good to know. Apparently that antivirus causes problems with a range of different software and one of them is Git.

**Comment by carlmontanari** [comment]
Hoping that this is sorted thanks to @Pavel910 comment here, so going to go ahead and close! Feel free to reopen if this can be tied back to any issue/bug here in devspace!
