### ISSUE TITLE
devspace upgrade fail / semver: Parse(): Version string empty

### ISSUE THREAD

**Issue by pablorsk** [loft-sh/devspace#1380]
**What happened?**  
```
$ devspace --version
devspace version 5.8.2
$ devspace upgrade
panic: semver: Parse(): Version string empty

goroutine 1 [running]:
github.com/blang/semver.MustParse(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/runner/work/devspace/devspace/vendor/github.com/blang/semver/semver.go:319 +0x245
github.com/loft-sh/devspace/pkg/devspace/upgrade.Upgrade(0x0, 0x0, 0x0, 0xc000d1d8c0)
	/Users/runner/work/devspace/devspace/pkg/devspace/upgrade/upgrade.go:159 +0x565
github.com/loft-sh/devspace/cmd.(*UpgradeCmd).Run(0xc0000a72d0, 0x34013e8, 0x0, 0x0, 0xc000d1d8c0, 0x34013e8, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/work/devspace/devspace/cmd/upgrade.go:48 +0xec
github.com/loft-sh/devspace/cmd.NewUpgradeCmd.func1(0xc000d1d8c0, 0x34013e8, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/work/devspace/devspace/cmd/upgrade.go:31 +0x71
github.com/spf13/cobra.(*Command).execute(0xc000d1d8c0, 0x34013e8, 0x0, 0x0, 0xc000d1d8c0, 0x34013e8)
	/Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000dc840, 0x34013e8, 0xc0000dc840, 0x0)
	/Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:887
github.com/loft-sh/devspace/cmd.Execute()
	/Users/runner/work/devspace/devspace/cmd/root.go:99 +0x7d
main.main()
	/Users/runner/work/devspace/devspace/main.go:20 +0xf7
```

**Local Environment:**  
- DevSpace Version: 5.8.2
- Operating System: linux

**Kubernetes Cluster:**  
- Cloud Provider: other
- Kubernetes Version: 1.15.5

**Comment by FabianKramm** [comment]
@pablorsk thanks for reporting this issue! In version `v5.8.2` was unfortunately a bug that resulted in this error message, you will need to upgrade via `devspace upgrade --version v5.10.0` (see [release](https://github.com/loft-sh/devspace/releases/tag/v5.8.4) for more info)
